### ISSUE TITLE
Translation: Needs Spanish translation

### ISSUE THREAD

**Issue by koenvervloesem** [koenvervloesem/snips-app-pick-something-random#6]
https://github.com/koenvervloesem/snips-app-pick-something-random/tree/master/translations

**Comment by christopherdufort** [comment]
Wanted to take this task, here are some questions:

- For the intents whats is "koan" in English or "Sanlokii" in French? They look like they are just names of contributors?

- Date formats change in different languages so for "MMMM D" if the day is before the month as is in french this is fine?

**Comment by koenvervloesem** [comment]
Hi Christopher,

- Yes you should change this to your username in the Snips Console.
- If you want to have the day before the month, use `RESULT_MONTH_DAY = "D MMMM"` like in the French translation indeed.

Let me know here if you have some other questions.

**Comment by koenvervloesem** [comment]
I'm closing this because I stopped the development of this app.
